services:
  platform-api:
    build:
      context: .  # <--- Dit puntje is cruciaal! Het zegt: gebruik de huidige map (root)
      dockerfile: platform-api/Dockerfile # <--- Wijs hier naar het pad van je Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PLATFORM_DB_HOST=platform-db
      - PLATFORM_DB_USER=${PLATFORM_DB_USER}
      - PLATFORM_DB_PASSWORD=${PLATFORM_DB_PASSWORD}
      - PLATFORM_DB_NAME=${PLATFORM_DB_NAME}
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./clients:/app/clients
       - ./scripts:/app/scripts
    depends_on:
      - platform-db

  platform-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${PLATFORM_DB_NAME}
      - POSTGRES_USER=${PLATFORM_DB_USER}
      - POSTGRES_PASSWORD=${PLATFORM_DB_PASSWORD}
    ports:
      - "5433:5432"

  tui:
    build: ./platform-tui
    container_name: platform-tui
    ports:
      - "2222:22"
    env_file:
      - .env
    volumes:
      - ./platform-tui/app.py:/app/app.py
      - ./platform-api/config.py:/app/config.py
      - .env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_HOST=${PLATFORM_DB_HOST}
      - DB_USER=${PLATFORM_DB_USER}
      - DB_PASS=${PLATFORM_DB_PASSWORD}
      - API_URL=http://api:8080
    depends_on:
      - platform-db