services:
  platform-api:
    build: ./platform-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PLATFORM_DB_HOST=platform-db
      - PLATFORM_DB_USER=${PLATFORM_DB_USER}
      - PLATFORM_DB_PASSWORD=${PLATFORM_DB_PASSWORD}
      - PLATFORM_DB_NAME=${PLATFORM_DB_NAME}
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./staging:/app/staging
       - ./deployments:/app/deployments
    depends_on:
      - platform-db

  platform-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${PLATFORM_DB_NAME}
      - POSTGRES_USER=${PLATFORM_DB_USER}
      - POSTGRES_PASSWORD=${PLATFORM_DB_PASSWORD}
    ports:
      - "5433:5432"