networks:
  net_voting_app_test:
    driver: bridge
services:
  app:
    environment: {}
    image: nginx:alpine
    networks:
    - net_voting_app_test
    ports:
    - 8081:80
    restart: unless-stopped
    volumes:
    - /app/staging/example-voting-app_20251227151806:/var/www/html
version: '3.8'
